from typing import Any

def ddspy_calc_key(*args, **kwargs) -> Any: ...
def ddspy_dispose(*args, **kwargs) -> Any: ...
def ddspy_dispose_handle(*args, **kwargs) -> Any: ...
def ddspy_dispose_handle_ts(*args, **kwargs) -> Any: ...
def ddspy_dispose_ts(*args, **kwargs) -> Any: ...
def ddspy_lookup_instance(*args, **kwargs) -> Any: ...
def ddspy_read(*args, **kwargs) -> Any: ...
def ddspy_read_endpoint(*args, **kwargs) -> Any: ...
def ddspy_read_handle(*args, **kwargs) -> Any: ...
def ddspy_read_next(*args, **kwargs) -> Any: ...
def ddspy_read_participant(*args, **kwargs) -> Any: ...
def ddspy_register_instance(*args, **kwargs) -> Any: ...
def ddspy_take(*args, **kwargs) -> Any: ...
def ddspy_take_endpoint(*args, **kwargs) -> Any: ...
def ddspy_take_handle(*args, **kwargs) -> Any: ...
def ddspy_take_next(*args, **kwargs) -> Any: ...
def ddspy_take_participant(*args, **kwargs) -> Any: ...
def ddspy_topic_create(*args, **kwargs) -> Any: ...
def ddspy_unregister_instance(*args, **kwargs) -> Any: ...
def ddspy_unregister_instance_handle(*args, **kwargs) -> Any: ...
def ddspy_unregister_instance_handle_ts(*args, **kwargs) -> Any: ...
def ddspy_unregister_instance_ts(*args, **kwargs) -> Any: ...
def ddspy_write(*args, **kwargs) -> Any: ...
def ddspy_write_ts(*args, **kwargs) -> Any: ...
def ddspy_writedispose(*args, **kwargs) -> Any: ...
def ddspy_writedispose_ts(*args, **kwargs) -> Any: ...
